"""Create complete database schema

Revision ID: 2d567847734c
Revises: 
Create Date: 2026-01-12 17:06:37.476315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d567847734c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('areas',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index('idx_areas_area_name', 'areas', ['area_name'], unique=False)
    op.create_index('idx_areas_upload_date', 'areas', ['upload_date'], unique=False)
    op.create_index(op.f('ix_areas_area_id'), 'areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_areas_area_name'), 'areas', ['area_name'], unique=False)
    op.create_table('login_logs',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_login_logs_log_id'), 'login_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_login_logs_phone_number'), 'login_logs', ['phone_number'], unique=False)
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volunteers_email', 'volunteers', ['email'], unique=False)
    op.create_index('idx_volunteers_politician_id', 'volunteers', ['politician_id'], unique=False)
    op.create_index(op.f('ix_volunteers_email'), 'volunteers', ['email'], unique=True)
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('household_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('colony', sa.String(length=255), nullable=True),
    sa.Column('family_members', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.String(length=255), nullable=True),
    sa.Column('aadhar', sa.String(length=255), nullable=True),
    sa.Column('voter_names', sa.Text(), nullable=True),
    sa.Column('voter_ages', sa.Text(), nullable=True),
    sa.Column('voter_relation', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('knows_corporator', sa.Boolean(), nullable=True),
    sa.Column('satisfied_with_corporator', sa.Boolean(), nullable=True),
    sa.Column('knows_politician', sa.Text(), nullable=True),
    sa.Column('supports_politician', sa.String(length=255), nullable=True),
    sa.Column('politician_visit_freq', sa.String(length=255), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('service_frequency', sa.String(length=255), nullable=True),
    sa.Column('service_satisfaction', sa.String(length=255), nullable=True),
    sa.Column('attended_events', sa.Boolean(), nullable=True),
    sa.Column('known_leaders', sa.Text(), nullable=True),
    sa.Column('income_range', sa.String(length=255), nullable=True),
    sa.Column('main_occupation', sa.String(length=255), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('housing_type', sa.String(length=255), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('volunteer_name', sa.String(length=255), nullable=True),
    sa.Column('corporator_division', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('person_image_url', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form_data_volunteer_id', 'form_data', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_form_data_id'), 'form_data', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('part_name_en', sa.String(length=255), nullable=True),
    sa.Column('part_name_v1', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_index(op.f('ix_parts_part_no'), 'parts', ['part_no'], unique=True)
    op.create_table('user_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area_id', name='uq_user_area')
    )
    op.create_index('idx_user_areas_area_id', 'user_areas', ['area_id'], unique=False)
    op.create_index('idx_user_areas_user_id', 'user_areas', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_areas_id'), 'user_areas', ['id'], unique=False)
    op.create_table('family_members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('form_data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('is_eligible_to_vote', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('voter_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['form_data_id'], ['form_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index('idx_family_members_form_data_id', 'family_members', ['form_data_id'], unique=False)
    op.create_index(op.f('ix_family_members_member_id'), 'family_members', ['member_id'], unique=False)
    op.create_table('voters',
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('epic_no', sa.String(length=50), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('slnoinpart', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(length=10), nullable=True),
    sa.Column('rln_fm_nm_en', sa.String(length=100), nullable=True),
    sa.Column('rln_l_nm_en', sa.String(length=100), nullable=True),
    sa.Column('rln_fm_nm_v1', sa.String(length=100), nullable=True),
    sa.Column('rln_l_nm_v1', sa.String(length=100), nullable=True),
    sa.Column('fm_name_en', sa.String(length=100), nullable=True),
    sa.Column('lastname_en', sa.String(length=100), nullable=True),
    sa.Column('fm_name_v1', sa.String(length=100), nullable=True),
    sa.Column('lastname_v1', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('mobile_no', sa.String(length=15), nullable=True),
    sa.Column('ac_no', sa.Integer(), nullable=True),
    sa.Column('section_no', sa.Integer(), nullable=True),
    sa.Column('pc_no', sa.Integer(), nullable=True),
    sa.Column('village_name_en', sa.String(length=100), nullable=True),
    sa.Column('village_name_v1', sa.String(length=100), nullable=True),
    sa.Column('tahsil_name_en', sa.String(length=100), nullable=True),
    sa.Column('police_name_en', sa.String(length=100), nullable=True),
    sa.Column('postoff_pin', sa.String(length=10), nullable=True),
    sa.Column('c_house_no', sa.String(length=50), nullable=True),
    sa.Column('c_house_no_v1', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('voter_id')
    )
    op.create_index(op.f('ix_voters_ac_no'), 'voters', ['ac_no'], unique=False)
    op.create_index(op.f('ix_voters_epic_no'), 'voters', ['epic_no'], unique=True)
    op.create_index(op.f('ix_voters_fm_name_en'), 'voters', ['fm_name_en'], unique=False)
    op.create_index(op.f('ix_voters_lastname_en'), 'voters', ['lastname_en'], unique=False)
    op.create_index(op.f('ix_voters_mobile_no'), 'voters', ['mobile_no'], unique=False)
    op.create_index(op.f('ix_voters_pc_no'), 'voters', ['pc_no'], unique=False)
    op.create_index(op.f('ix_voters_tahsil_name_en'), 'voters', ['tahsil_name_en'], unique=False)
    op.create_index(op.f('ix_voters_village_name_en'), 'voters', ['village_name_en'], unique=False)
    op.create_index(op.f('ix_voters_voter_id'), 'voters', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_voter_id'), table_name='voters')
    op.drop_index(op.f('ix_voters_village_name_en'), table_name='voters')
    op.drop_index(op.f('ix_voters_tahsil_name_en'), table_name='voters')
    op.drop_index(op.f('ix_voters_pc_no'), table_name='voters')
    op.drop_index(op.f('ix_voters_mobile_no'), table_name='voters')
    op.drop_index(op.f('ix_voters_lastname_en'), table_name='voters')
    op.drop_index(op.f('ix_voters_fm_name_en'), table_name='voters')
    op.drop_index(op.f('ix_voters_epic_no'), table_name='voters')
    op.drop_index(op.f('ix_voters_ac_no'), table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_family_members_member_id'), table_name='family_members')
    op.drop_index('idx_family_members_form_data_id', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_user_areas_id'), table_name='user_areas')
    op.drop_index('idx_user_areas_user_id', table_name='user_areas')
    op.drop_index('idx_user_areas_area_id', table_name='user_areas')
    op.drop_table('user_areas')
    op.drop_index(op.f('ix_parts_part_no'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_form_data_id'), table_name='form_data')
    op.drop_index('idx_form_data_volunteer_id', table_name='form_data')
    op.drop_table('form_data')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_email'), table_name='volunteers')
    op.drop_index('idx_volunteers_politician_id', table_name='volunteers')
    op.drop_index('idx_volunteers_email', table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_login_logs_phone_number'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_log_id'), table_name='login_logs')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_areas_area_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_id'), table_name='areas')
    op.drop_index('idx_areas_upload_date', table_name='areas')
    op.drop_index('idx_areas_area_name', table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
