"""update the family member table with adding another column voter_id

Revision ID: 419d589f2c34
Revises: 95911ef40d07
Create Date: 2026-01-10 17:50:09.221924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419d589f2c34'
down_revision: Union[str, Sequence[str], None] = '95911ef40d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('voter_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_members', 'voter_id')
    # ### end Alembic commands ###
