"""inital cretion of tables

Revision ID: 503e308da423
Revises: 
Create Date: 2026-02-13 12:41:37.548321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503e308da423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('areas',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index('idx_areas_area_name', 'areas', ['area_name'], unique=False)
    op.create_index('idx_areas_upload_date', 'areas', ['upload_date'], unique=False)
    op.create_index(op.f('ix_areas_area_id'), 'areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_areas_area_name'), 'areas', ['area_name'], unique=False)
    op.create_table('login_logs',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_login_logs_log_id'), 'login_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_login_logs_phone_number'), 'login_logs', ['phone_number'], unique=False)
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volunteers_email', 'volunteers', ['email'], unique=False)
    op.create_index('idx_volunteers_politician_id', 'volunteers', ['politician_id'], unique=False)
    op.create_index(op.f('ix_volunteers_email'), 'volunteers', ['email'], unique=True)
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('household_name', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('caste', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('colony', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('family_members', sa.Integer(), nullable=True),
    sa.Column('family_members_count', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.String(length=255), nullable=True),
    sa.Column('aadhar', sa.String(length=255), nullable=True),
    sa.Column('voter_names', sa.Text(), nullable=True),
    sa.Column('voter_ages', sa.Text(), nullable=True),
    sa.Column('voter_relation', sa.Text(), nullable=True),
    sa.Column('is_voted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('voting_status', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('knows_corporator', sa.Boolean(), nullable=True),
    sa.Column('corporator_name', sa.String(length=255), nullable=True),
    sa.Column('knows_politician', sa.Text(), nullable=True),
    sa.Column('other_politicians_known', sa.Text(), nullable=True),
    sa.Column('current_party_support', sa.String(length=255), nullable=True),
    sa.Column('favourite_party', sa.String(length=255), nullable=True),
    sa.Column('services_received', sa.Text(), nullable=True),
    sa.Column('service_frequency', sa.String(length=255), nullable=True),
    sa.Column('politician_visit_freq', sa.String(length=255), nullable=True),
    sa.Column('satisfaction_with_corporator', sa.String(length=50), nullable=True),
    sa.Column('satisfaction_with_service', sa.String(length=50), nullable=True),
    sa.Column('attended_events', sa.Boolean(), nullable=True),
    sa.Column('work_done_in_ward', sa.Boolean(), nullable=True),
    sa.Column('work_details', sa.Text(), nullable=True),
    sa.Column('income_range', sa.String(length=255), nullable=True),
    sa.Column('main_occupation', sa.String(length=255), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('highest_education', sa.Text(), nullable=True),
    sa.Column('housing_type', sa.String(length=255), nullable=True),
    sa.Column('govt_schemes', sa.Text(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('volunteer_name', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('corporator_division', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('person_image_url', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_accuracy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("voting_status IS NULL OR voting_status IN ('red', 'yellow', 'green')", name='check_voting_status'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form_data_is_voted', 'form_data', ['is_voted'], unique=False)
    op.create_index('idx_form_data_mobile_number', 'form_data', ['mobile_number'], unique=False)
    op.create_index('idx_form_data_phone_number', 'form_data', ['phone_number'], unique=False)
    op.create_index('idx_form_data_volunteer_id', 'form_data', ['volunteer_id'], unique=False)
    op.create_index('idx_form_data_voting_status', 'form_data', ['voting_status'], unique=False)
    op.create_index(op.f('ix_form_data_id'), 'form_data', ['id'], unique=False)
    op.create_index(op.f('ix_form_data_is_voted'), 'form_data', ['is_voted'], unique=False)
    op.create_index(op.f('ix_form_data_phone_number'), 'form_data', ['phone_number'], unique=False)
    op.create_index(op.f('ix_form_data_voting_status'), 'form_data', ['voting_status'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('part_name_en', sa.String(length=255), nullable=True),
    sa.Column('part_name_v1', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index('idx_part_area_id', 'parts', ['area_id'], unique=False)
    op.create_index('idx_part_area_part_no', 'parts', ['area_id', 'part_no'], unique=False)
    op.create_index('idx_part_no', 'parts', ['part_no'], unique=False)
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_index(op.f('ix_parts_part_no'), 'parts', ['part_no'], unique=False)
    op.create_table('user_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area_id', name='uq_user_area')
    )
    op.create_index('idx_user_areas_area_id', 'user_areas', ['area_id'], unique=False)
    op.create_index('idx_user_areas_user_id', 'user_areas', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_areas_id'), 'user_areas', ['id'], unique=False)
    op.create_table('volunteer_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_locations', 'volunteer_locations', ['is_active', 'timestamp'], unique=False)
    op.create_index('idx_volunteer_active', 'volunteer_locations', ['volunteer_id', 'is_active'], unique=False)
    op.create_index('idx_volunteer_timestamp', 'volunteer_locations', ['volunteer_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_volunteer_locations_id'), 'volunteer_locations', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_locations_timestamp'), 'volunteer_locations', ['timestamp'], unique=False)
    op.create_table('family_members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('form_data_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('is_eligible_to_vote', sa.Boolean(), nullable=True),
    sa.Column('voter_id', sa.String(length=50), nullable=True),
    sa.Column('aadhar_id', sa.String(length=50), nullable=True),
    sa.Column('relation_to_head', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['form_data_id'], ['form_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_family_members_member_id'), 'family_members', ['member_id'], unique=False)
    op.create_table('voters',
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('epic_no', sa.String(length=50), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('ward_no', sa.String(length=10), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=200), nullable=False),
    sa.Column('polling_station_no', sa.String(length=10), nullable=False),
    sa.Column('polling_station_location', sa.Text(), nullable=True),
    sa.Column('serial_no', sa.String(length=10), nullable=True),
    sa.Column('voter_name', sa.String(length=200), nullable=True),
    sa.Column('relation_name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('house_no', sa.String(length=100), nullable=True),
    sa.Column('date_time', sa.String(length=100), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('voter_id')
    )
    op.create_index('idx_voters_epic_no', 'voters', ['epic_no'], unique=False)
    op.create_index('idx_voters_house_no', 'voters', ['house_no'], unique=False)
    op.create_index('idx_voters_municipality', 'voters', ['municipality'], unique=False)
    op.create_index('idx_voters_part_id', 'voters', ['part_id'], unique=False)
    op.create_index('idx_voters_phone_number', 'voters', ['phone_number'], unique=False)
    op.create_index('idx_voters_polling_station', 'voters', ['polling_station_no'], unique=False)
    op.create_index('idx_voters_voter_name', 'voters', ['voter_name'], unique=False)
    op.create_index('idx_voters_ward_no', 'voters', ['ward_no'], unique=False)
    op.create_index(op.f('ix_voters_epic_no'), 'voters', ['epic_no'], unique=True)
    op.create_index(op.f('ix_voters_municipality'), 'voters', ['municipality'], unique=False)
    op.create_index(op.f('ix_voters_phone_number'), 'voters', ['phone_number'], unique=False)
    op.create_index(op.f('ix_voters_polling_station_no'), 'voters', ['polling_station_no'], unique=False)
    op.create_index(op.f('ix_voters_voter_id'), 'voters', ['voter_id'], unique=False)
    op.create_index(op.f('ix_voters_voter_name'), 'voters', ['voter_name'], unique=False)
    op.create_index(op.f('ix_voters_ward_no'), 'voters', ['ward_no'], unique=False)
    op.create_table('voter_change_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('epic_no', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.voter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_voter_change_logs_epic_no', 'voter_change_logs', ['epic_no'], unique=False)
    op.create_index('idx_voter_change_logs_timestamp', 'voter_change_logs', ['change_timestamp'], unique=False)
    op.create_index('idx_voter_change_logs_user_id', 'voter_change_logs', ['user_id'], unique=False)
    op.create_index('idx_voter_change_logs_volunteer_id', 'voter_change_logs', ['volunteer_id'], unique=False)
    op.create_index('idx_voter_change_logs_voter_id', 'voter_change_logs', ['voter_id'], unique=False)
    op.create_index(op.f('ix_voter_change_logs_change_timestamp'), 'voter_change_logs', ['change_timestamp'], unique=False)
    op.create_index(op.f('ix_voter_change_logs_epic_no'), 'voter_change_logs', ['epic_no'], unique=False)
    op.create_index(op.f('ix_voter_change_logs_log_id'), 'voter_change_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voter_change_logs_log_id'), table_name='voter_change_logs')
    op.drop_index(op.f('ix_voter_change_logs_epic_no'), table_name='voter_change_logs')
    op.drop_index(op.f('ix_voter_change_logs_change_timestamp'), table_name='voter_change_logs')
    op.drop_index('idx_voter_change_logs_voter_id', table_name='voter_change_logs')
    op.drop_index('idx_voter_change_logs_volunteer_id', table_name='voter_change_logs')
    op.drop_index('idx_voter_change_logs_user_id', table_name='voter_change_logs')
    op.drop_index('idx_voter_change_logs_timestamp', table_name='voter_change_logs')
    op.drop_index('idx_voter_change_logs_epic_no', table_name='voter_change_logs')
    op.drop_table('voter_change_logs')
    op.drop_index(op.f('ix_voters_ward_no'), table_name='voters')
    op.drop_index(op.f('ix_voters_voter_name'), table_name='voters')
    op.drop_index(op.f('ix_voters_voter_id'), table_name='voters')
    op.drop_index(op.f('ix_voters_polling_station_no'), table_name='voters')
    op.drop_index(op.f('ix_voters_phone_number'), table_name='voters')
    op.drop_index(op.f('ix_voters_municipality'), table_name='voters')
    op.drop_index(op.f('ix_voters_epic_no'), table_name='voters')
    op.drop_index('idx_voters_ward_no', table_name='voters')
    op.drop_index('idx_voters_voter_name', table_name='voters')
    op.drop_index('idx_voters_polling_station', table_name='voters')
    op.drop_index('idx_voters_phone_number', table_name='voters')
    op.drop_index('idx_voters_part_id', table_name='voters')
    op.drop_index('idx_voters_municipality', table_name='voters')
    op.drop_index('idx_voters_house_no', table_name='voters')
    op.drop_index('idx_voters_epic_no', table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_family_members_member_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_volunteer_locations_timestamp'), table_name='volunteer_locations')
    op.drop_index(op.f('ix_volunteer_locations_id'), table_name='volunteer_locations')
    op.drop_index('idx_volunteer_timestamp', table_name='volunteer_locations')
    op.drop_index('idx_volunteer_active', table_name='volunteer_locations')
    op.drop_index('idx_active_locations', table_name='volunteer_locations')
    op.drop_table('volunteer_locations')
    op.drop_index(op.f('ix_user_areas_id'), table_name='user_areas')
    op.drop_index('idx_user_areas_user_id', table_name='user_areas')
    op.drop_index('idx_user_areas_area_id', table_name='user_areas')
    op.drop_table('user_areas')
    op.drop_index(op.f('ix_parts_part_no'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_index('idx_part_no', table_name='parts')
    op.drop_index('idx_part_area_part_no', table_name='parts')
    op.drop_index('idx_part_area_id', table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_form_data_voting_status'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_phone_number'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_is_voted'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_id'), table_name='form_data')
    op.drop_index('idx_form_data_voting_status', table_name='form_data')
    op.drop_index('idx_form_data_volunteer_id', table_name='form_data')
    op.drop_index('idx_form_data_phone_number', table_name='form_data')
    op.drop_index('idx_form_data_mobile_number', table_name='form_data')
    op.drop_index('idx_form_data_is_voted', table_name='form_data')
    op.drop_table('form_data')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_email'), table_name='volunteers')
    op.drop_index('idx_volunteers_politician_id', table_name='volunteers')
    op.drop_index('idx_volunteers_email', table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_login_logs_phone_number'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_log_id'), table_name='login_logs')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_areas_area_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_area_id'), table_name='areas')
    op.drop_index('idx_areas_upload_date', table_name='areas')
    op.drop_index('idx_areas_area_name', table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
