"""updated the vform data table removed the head voters  

Revision ID: 5f7429f48e31
Revises: 49817a59e11e
Create Date: 2026-02-18 18:36:36.727651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7429f48e31'
down_revision: Union[str, Sequence[str], None] = '49817a59e11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_form_data_head_voter_id'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_head_voter_id'), table_name='form_data')
    op.drop_column('form_data', 'head_voter_relation')
    op.drop_column('form_data', 'head_voter_name')
    op.drop_column('form_data', 'head_voter_id')
    op.drop_column('form_data', 'head_aadhar')
    op.drop_column('form_data', 'head_voter_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('head_voter_age', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('form_data', sa.Column('head_aadhar', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('form_data', sa.Column('head_voter_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('form_data', sa.Column('head_voter_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('form_data', sa.Column('head_voter_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_form_data_head_voter_id'), 'form_data', ['head_voter_id'], unique=False)
    op.create_index(op.f('idx_form_data_head_voter_id'), 'form_data', ['head_voter_id'], unique=False)
    # ### end Alembic commands ###
