"""updated the voter table with eng 

Revision ID: e3122eda5795
Revises: 503e308da423
Create Date: 2026-02-13 15:43:42.261298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3122eda5795'
down_revision: Union[str, Sequence[str], None] = '503e308da423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('district_en', sa.String(length=100), nullable=True))
    op.add_column('voters', sa.Column('municipality_en', sa.String(length=200), nullable=True))
    op.add_column('voters', sa.Column('polling_station_location_en', sa.Text(), nullable=True))
    op.add_column('voters', sa.Column('voter_name_en', sa.String(length=200), nullable=True))
    op.add_column('voters', sa.Column('relation_name_en', sa.String(length=200), nullable=True))
    op.create_index('idx_voters_municipality_en', 'voters', ['municipality_en'], unique=False)
    op.create_index('idx_voters_voter_name_en', 'voters', ['voter_name_en'], unique=False)
    op.create_index(op.f('ix_voters_municipality_en'), 'voters', ['municipality_en'], unique=False)
    op.create_index(op.f('ix_voters_voter_name_en'), 'voters', ['voter_name_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_voter_name_en'), table_name='voters')
    op.drop_index(op.f('ix_voters_municipality_en'), table_name='voters')
    op.drop_index('idx_voters_voter_name_en', table_name='voters')
    op.drop_index('idx_voters_municipality_en', table_name='voters')
    op.drop_column('voters', 'relation_name_en')
    op.drop_column('voters', 'voter_name_en')
    op.drop_column('voters', 'polling_station_location_en')
    op.drop_column('voters', 'municipality_en')
    op.drop_column('voters', 'district_en')
    # ### end Alembic commands ###
