"""updated the vform data table removed phone number  

Revision ID: f1c560ac074f
Revises: 5f7429f48e31
Create Date: 2026-02-18 19:17:32.053094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c560ac074f'
down_revision: Union[str, Sequence[str], None] = '5f7429f48e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_form_data_phone_number'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_phone_number'), table_name='form_data')
    op.drop_column('form_data', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_form_data_phone_number'), 'form_data', ['phone_number'], unique=False)
    op.create_index(op.f('idx_form_data_phone_number'), 'form_data', ['phone_number'], unique=False)
    # ### end Alembic commands ###
